version: '3.9'
services:
  flask_api:
    build: ./ads-api
    container_name: flask_api
    ports:
      - "5000:5000"

  react_app:
    build: ./ads-ui
    container_name: react_app
    ports:
      - "8080:80"