version: '3.9'

services:
  redis:
    image: "redis:latest"
    container_name: redis_cache
    ports:
      - "6379:6379"

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq_service
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: "mongo:latest"
    container_name: mongodb_service
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - /var/lib/mongodb:/data/db

  # app:
  #   build:
  #     context: .
  #   container_name: app_service
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - redis
  #     - rabbitmq
  #     - mongodb

volumes:
  mongodb_data:
